name: benchmarks 

on: 
  push:
  pull_request:
    types: [labeled]
    paths-ignore:
      - 'tests/benchmarks/.benchmarks/**'
      - 'tests/benchmarks/Figures/**'
      - 'docs/**'
  workflow_dispatch:


jobs:
  build:
    if: ${{ github.event.label.name == 'run_benchmarks' && github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/requirements.txt
      - name: Benchmark with pytest-benchmark
        run: |
          pwd
          lscpu
          cd tests/benchmarks
          python -m pytest benchmark.py --benchmark-autosave
      - name: Save Benchmark Results
        run: |
          pwd
          cd tests/benchmarks
          python read_bench_results.py
      - name: Commit the results and the figure to the benchmark_results branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: benchmark_results
          FOLDER: tests/benchmarks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLEAR_GLOBS_FILE: ".clear-target-files"
          MESSAGE: "Commit Benchmark results for commit {sha} with the following commit message:\n {msg}	 " # The commit message
          
