name: JAX version tests

on:
  pull_request:
    types: [labeled]
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.label.name == 'test_jax' && github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        jaxlib-version: [0.1.60, 0.1.62, 0.1.64, 0.1.66, 0.1.68, 0.1.70, 0.1.72, 0.1.76]
        jax-version: [0.2.0, 0.2.5, 0.2.10, 0.2.15, 0.2.20, 0.2.25, 0.2.28]
        include:
          - jaxlib-version: 0.3.0
            jax-version: 0.3.0	  
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/requirements.txt
          pip uninstall flatbuffers -y
          pip install "jaxlib==${{ matrix.jaxlib-version }}"
          pip install "jax==${{ matrix.jax-version }}"	  
      - name: Test with pytest
        run: |
          pwd
          lscpu
          python -m pytest --durations=0 --cov --mpl
